### ISSUE TITLE
asciidoctor-bib fails with current asciidoctor

### ISSUE THREAD

**Issue by clintgibler** [petercrlane/asciidoc-bib#11]
When I try to run `asciidoctor-bib -b main.bib foo.adoc` it fails as follows:

```
.../gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362:in `rescue in load': asciidoctor: FAILED: foo.adoc: Failed to parse source, undefined method `preprocessor' for AsciidocBib::Asciidoctor:Module (NoMethodError)
	from .../gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1281:in `load'
	from .../gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458:in `convert'
	from .../gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562:in `convert_file'
	from ~/asciidoc-bib/lib/asciidoc-bib/asciidoctor.rb:67:in `run'
	from ~/asciidoc-bib/bin/asciidoctor-bib:17:in `<main>'
```

Running environment:
- OS X - 10.9.5
- Ruby - 2.0.0p481
- asciidoc-bib code from master branch, asciidoctor 1.5.2

`asciidoc-bib` process the same file with no problems. 

My guess is that asciidoctor changed the [extension](http://asciidoctor.org/docs/user-manual/#extensions) API somehow in an incompatible way.

**Comment by andreabedini** [comment]
I'm experiencing the same problem, is #12 going to get merged?
