### ISSUE TITLE
Cannot use with asciidoctor options

### ISSUE THREAD

**Issue by wackywendell** [petercrlane/asciidoc-bib#14]
If I want to use the [reveal.js backend](https://github.com/asciidoctor/asciidoctor-reveal.js), I normally would run

```
$ asciidoctor -T templates/slim MYFILE.adoc
```

As far as I can tell, this is incompatible with `asciidoc-bib`: there's no way to use the `-T` option (or any other `asciidoctor` command-line option) with `asciidoctor-bib`:

```
asciidoctor-bib -b bibliography.bib  -T templates/slim index.adoc
Usage: asciidoctor-bib filename
    -h, --help                       help message
    -b, --bibfile FILE               location of bib file
    -n, --no-links                   do not add internal links
        --numeric-alphabetic-order
                                     sort numeric styles in alphabetical order (DEFAULT)
        --numeric-appearance-order
                                     sort numeric styles in order of appearance
    -s, --style STYLE                reference style
    -v, --version                    show version
```

Anyways, thanks for making this! Its a pretty cool addition to asciidoctor, and if I could integrate it in more easily, I would really enjoy using this!

**Comment by petercrlane** [comment]
Yes, this is a limitation, and something I hope to fix later when I have time.

However, you can use asciidoc-bib to produce a file with the reference/citation information included, and then pass this to asciidoctor.

This is easily scriptable. i.e.

    asciidoc-bib MYFILE.adoc
    asciidoctor -T templates/slim MYFILE-ref.adoc

(Note: this is the 'usual way' when using asciidoc itself.)

**Comment by wackywendell** [comment]
> you can use asciidoc-bib to produce a file with the reference/citation information included

Ah! That makes sense! Thanks!
